"use client";

import { useMemo, useState } from "react";
import {
  AlertTriangle, ArrowRight, BadgeCheck, Banknote, BarChart3, Bot, BriefcaseBusiness,
  CalendarDays, Check, CheckCircle2, ChevronRight, CircleDollarSign, ClipboardCheck,
  Clock3, Download, FileText, Landmark, MessageSquareText, Network, RefreshCw,
  Search, Send, ShieldCheck, Sparkles, Upload, UserRoundCheck, Users, WalletCards,
} from "lucide-react";
import { Progress } from "@/components/ui/progress";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";

const steps = ["Period", "Earnings", "Validate", "Lock FX", "Calculate", "Review", "Approve", "Funding", "Release", "Reconcile"];
const backendStates = ["Draft", "Draft", "Validating", "Validating", "Funding required", "Funding required", "Approved", "Funded", "Processing / Paid", "Reconciled"];
const stepCopy = [
  ["Choose the payroll period", "Confirm the dates, pay frequency and payment date."],
  ["Sync attendance and review earnings", "Use Personal-account work events, then review pay, overtime, benefits and approved adjustments."],
  ["Validate employee records", "Resolve identity, destination, attendance and deduction exceptions."],
  ["Lock the payroll exchange rate", "PAYE will use the approved LRD rate and source shown below."],
  ["Calculate payroll", "Convert taxable USD earnings, combine LRD earnings and calculate PAYE in LRD."],
  ["Review every employee", "Compare gross income, deductions, net entitlement and prior-period changes."],
  ["Maker-checker approval", "Submit the locked version to an independent authorized officer."],
  ["Confirm cleared funding", "Check LRD and USD requirements separately before automatic release."],
  ["Release payment instructions", "Send salaries and liabilities with an idempotent payroll reference."],
  ["Reconcile outcomes", "Track settled, pending, failed, returned and reversed transactions."],
];

function Head({eyebrow,title,copy,action,onAction}:{eyebrow:string;title:string;copy:string;action?:string;onAction?:()=>void}){
  return <header className="page-head"><div><span>{eyebrow}</span><h1>{title}</h1><p>{copy}</p></div>{action&&<button className="primary compact" onClick={onAction}>{action}<ArrowRight/></button>}</header>;
}

export function NextAction({go}:{go:(page:any)=>void}){
  return <section className="next-action"><div className="next-action-icon"><AlertTriangle/></div><div><small>NEXT REQUIRED ACTION</small><h2>Resolve 6 employee exceptions</h2><p>Payroll calculation is ready, but identity and attendance issues must be cleared before renewed approval.</p></div><div className="next-action-meta"><span><b>6</b> open cases</span><span><b>Aug 30</b> funding deadline</span></div><button onClick={()=>go("Exception Center")}>Open exception queue <ArrowRight/></button></section>;
}

export function PayrollStudio({employees,openEmployee,notify}:{employees:any[];openEmployee:(e:any)=>void;notify:(m:string)=>void}){
  const [step,setStep]=useState(0),[rate,setRate]=useState("199.25"),[locked,setLocked]=useState(false),[validated,setValidated]=useState(false);
  const current=stepCopy[step];
  return <><Head eyebrow="GUIDED PAYROLL" title="Run August payroll" copy="A resumable, controlled workflow from pay-period setup through reconciliation." action="Save & exit" onAction={()=>notify("Payroll progress saved")}/>
    <section className="guided-progress"><div><b>{step+1} of 10</b><span>{Math.round(((step+1)/10)*100)}% complete</span></div><Progress value={((step+1)/10)*100}/></section>
    <section className="advanced-stepper">{steps.map((s,i)=><button key={s} className={i<step?"done":i===step?"current":""} onClick={()=>setStep(i)}><i>{i<step?<Check/>:i+1}</i><span>{s}</span><small>{backendStates[i]}</small></button>)}</section>
    <section className="studio-grid"><article className="panel step-workspace"><div className="section-heading"><span><BriefcaseBusiness/></span><div><small>CURRENT STEP</small><h2>{current[0]}</h2><p>{current[1]}</p></div></div>
      {step===0&&<div className="control-grid"><label>Pay period<Select defaultValue="aug"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="aug">August 1–31, 2026</SelectItem><SelectItem value="sep">September 1–30, 2026</SelectItem></SelectContent></Select></label><label>Payment date<input type="date" defaultValue="2026-08-31"/></label><label>Frequency<Select defaultValue="monthly"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="monthly">Monthly</SelectItem><SelectItem value="biweekly">Biweekly</SelectItem></SelectContent></Select></label></div>}
      {step===1&&<div className="upload-zone"><RefreshCw/><b>Sync employee attendance</b><p>Verified Personal-account events sync automatically; upload earnings only when needed.</p><button onClick={()=>notify("Personal-account attendance synced; earnings source opened")}>Sync & review earnings</button></div>}
      {step===2&&<div className="validation-board"><div><b>{validated?"248":"242"}</b><span>employees ready</span></div><div><b>{validated?"0":"6"}</b><span>exceptions</span></div><button onClick={()=>{setValidated(true);notify("Validation rerun completed")}}><RefreshCw/>Run validation</button></div>}
      {step===3&&<><div className="control-grid"><label>Approved FX rate<input value={rate} onChange={e=>{setRate(e.target.value);setLocked(false)}}/></label><label>Rate source<Select defaultValue="bank"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="bank">Partner Bank FX Feed</SelectItem><SelectItem value="cbl">CBL reference rate</SelectItem><SelectItem value="manual">Authorized manual rate</SelectItem></SelectContent></Select></label></div><button className="primary" onClick={()=>{setLocked(true);notify("Exchange rate locked for this payroll")}}>{locked?<Check/>:<ShieldCheck/>}{locked?"Rate locked":"Lock exchange rate"}</button></>}
      {step>=4&&<div className="calculation-summary">{[["Taxable gross","20,600,000 LRD"],["PAYE liability","2,060,000 LRD"],["NASSCORP","1,840,000 LRD"],["Employee net pay","13,206,500 LRD + 1,125 USD"],["Tax rule version","LRA PAYE v2026.08 · effective Aug 1"]].map(x=><div key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</div>}
      <footer className="wizard-actions"><button disabled={step===0} onClick={()=>setStep(v=>Math.max(0,v-1))}>Back</button><button className="primary" onClick={()=>{if(step<9)setStep(v=>v+1);else notify("Payroll reconciliation completed")}}>{step===9?"Complete payroll":"Continue"}<ArrowRight/></button></footer>
    </article>
    <aside className="panel payroll-checklist"><h3>Readiness checklist</h3>{[["Employee identity","245 / 248"],["Attendance","243 / 248"],["Payment destinations","248 / 248"],["Loan schedules","94 / 96"],["Benefit elections","216 / 248"]].map((x,i)=><button key={x[0]} onClick={()=>notify(`${x[0]} detail opened`)}><span className={i<2?"warn":"ok"}>{i<2?<AlertTriangle/>:<CheckCircle2/>}</span><div><b>{x[0]}</b><small>{x[1]} ready</small></div><ChevronRight/></button>)}<aside><ShieldCheck/><p>Changes after approval cancel the locked version and require renewed approval.</p></aside></aside>
    </section>
    <article className="panel employee-investigation"><div className="section-heading"><span><Users/></span><div><small>EMPLOYEE REVIEW</small><h2>Calculation investigation</h2><p>Select an employee to inspect gross income, deductions, net pay and prior-period changes.</p></div></div><div className="investigation-list">{employees.map(e=><button key={e.id} onClick={()=>openEmployee(e)}><span>{e.name.split(" ").map((n:string)=>n[0]).join("")}</span><div><b>{e.name}</b><small>{e.currency} payroll · {e.department}</small></div><strong>{e.currency==="USD"?`${e.netUSD.toFixed(2)} USD`:`${e.netLRD.toLocaleString()} LRD`}</strong><i className={e.status==="Ready"?"ok":"warn"}>{e.status}</i><ChevronRight/></button>)}</div></article>
  </>;
}

export function ExceptionCenter({notify}:{notify:(m:string)=>void}){
  const seed=[
    {id:"CASE-1042",person:"Hawa Sirleaf",issue:"Missing TIN",owner:"Hawa Sirleaf",due:"Today",impact:"LRA PAYE file blocked",status:"Open"},
    {id:"CASE-1043",person:"Kelvin Freeman",issue:"Attendance mismatch",owner:"Martha Kallon",due:"Today",impact:"Gross pay may change",status:"Open"},
    {id:"CASE-1044",person:"Samuel Toe",issue:"Loan deduction variance",owner:"James Doe",due:"Aug 29",impact:"Lender payment held",status:"Investigating"},
    {id:"CASE-1045",person:"Fatu Brown",issue:"Missing NASSCORP ID",owner:"Unassigned",due:"Aug 29",impact:"NASSCORP file blocked",status:"Open"},
  ];
  const [cases,setCases]=useState(seed),[selected,setSelected]=useState(seed[0]),[note,setNote]=useState("");
  const update=(id:string,status:string)=>{setCases(v=>v.map(c=>c.id===id?{...c,status}:c));setSelected(v=>({...v,status}));notify(`Case marked ${status.toLowerCase()}`)};
  return <><Head eyebrow="OPERATIONS CASEWORK" title="Exception resolution center" copy="Assign, investigate and resolve payroll blockers with a complete internal record." action="Export queue" onAction={()=>notify("Exception queue exported")}/>
    <section className="case-layout"><article className="panel case-queue"><div className="table-tools"><div><Search/><input placeholder="Search cases or employees"/></div><Select defaultValue="all"><SelectTrigger className="filter-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All priorities</SelectItem><SelectItem value="high">High priority</SelectItem><SelectItem value="mine">Assigned to me</SelectItem></SelectContent></Select></div>{cases.map(c=><button key={c.id} className={selected.id===c.id?"selected":""} onClick={()=>setSelected(c)}><span className="case-icon"><AlertTriangle/></span><div><small>{c.id} · due {c.due}</small><b>{c.person}</b><p>{c.issue}</p></div><i className={`status ${c.status.toLowerCase()}`}>{c.status}</i><ChevronRight/></button>)}</article>
    <article className="panel case-detail"><div className="section-heading"><span><ClipboardCheck/></span><div><small>{selected.id}</small><h2>{selected.issue}</h2><p>{selected.person} · {selected.impact}</p></div></div><div className="detail-grid"><div><span>Assigned officer</span><b>{selected.owner}</b></div><div><span>Deadline</span><b>{selected.due}</b></div><div><span>Payroll impact</span><b>{selected.impact}</b></div><div><span>Status</span><b>{selected.status}</b></div></div><label>Internal case note<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Record investigation details or next steps"/></label><div className="case-actions"><button onClick={()=>notify("Supporting-document upload opened")}><Upload/>Add document</button><button onClick={()=>notify("Employee contact task created")}><MessageSquareText/>Contact employee</button><button className="primary" onClick={()=>update(selected.id,"Resolved")}><Check/>Resolve case</button></div></article></section>
  </>;
}

export function FundingSimulator({notify}:{notify:(m:string)=>void}){
  const [rate,setRate]=useState(199.25),[headcount,setHeadcount]=useState(248),[usd,setUsd]=useState(1125);
  const lrd=18450000+(headcount-248)*74200+(rate-199.25)*usd;
  return <><Head eyebrow="WHAT-IF PLANNING" title="Payroll funding simulator" copy="Model headcount, exchange-rate and currency scenarios before changing the approved payroll." action="Save scenario" onAction={()=>notify("Funding scenario saved")}/><section className="simulator-layout"><article className="panel simulator-controls"><label>Employees <input type="range" min="230" max="280" value={headcount} onChange={e=>setHeadcount(Number(e.target.value))}/><b>{headcount}</b></label><label>LRD per USD <input type="number" value={rate} onChange={e=>setRate(Number(e.target.value))}/></label><label>USD net salaries <input type="number" value={usd} onChange={e=>setUsd(Number(e.target.value))}/></label><div className="toggle-row"><span>Include employer benefit contributions</span><Switch defaultChecked onCheckedChange={value=>notify(`Employer benefits ${value?"included":"excluded"}`)}/></div><div className="toggle-row"><span>Include payment-network fees</span><Switch defaultChecked onCheckedChange={value=>notify(`Payment-network fees ${value?"included":"excluded"}`)}/></div></article><article className="scenario-card"><small>PROJECTED TOTAL REQUIREMENT</small><h2>{Math.round(lrd).toLocaleString()} LRD</h2><p>plus {usd.toLocaleString()} USD held separately</p><div><span>Cleared LRD</span><b>16,910,000 LRD</b></div><div><span>Projected LRD gap</span><b className="red-text">{Math.max(0,Math.round(lrd-16910000)).toLocaleString()} LRD</b></div><div><span>Rate sensitivity</span><b>{Math.round((rate-199.25)*usd).toLocaleString()} LRD</b></div><button onClick={()=>notify("Scenario compared with approved payroll")}>Compare with approved payroll <ArrowRight/></button></article></section></>;
}

export function ReconciliationCenter({notify}:{notify:(m:string)=>void}){
  const seed=[
    {id:"PAY-88421",name:"Martha Kallon",rail:"Prospeva Wallet",amount:"120,720 LRD + 432 USD",status:"Settled"},
    {id:"PAY-88422",name:"James Doe",rail:"UBA via IIPS",amount:"977.18 USD",status:"Pending"},
    {id:"PAY-88423",name:"Hawa Sirleaf",rail:"Orange Money",amount:"184,800 LRD",status:"Failed"},
    {id:"PAY-88424",name:"Samuel Toe",rail:"Prospeva Wallet",amount:"108,500 LRD + 336 USD",status:"Settled"},
    {id:"PAY-88425",name:"LRA PAYE",rail:"IIPS / NEPS",amount:"2,060,000 LRD",status:"Settled"},
  ];
  const [items,setItems]=useState(seed),[filter,setFilter]=useState("All");const shown=filter==="All"?items:items.filter(x=>x.status===filter);
  const retry=(id:string)=>{setItems(v=>v.map(x=>x.id===id?{...x,status:"Pending"}:x));notify("Only the failed instruction was resubmitted")};
  return <><Head eyebrow="DESTINATION-LEVEL CONTROL" title="Payment reconciliation" copy="Track every salary and liability without repeating successful payments." action="Download reconciliation" onAction={()=>notify("Reconciliation report prepared")}/><section className="recon-stats">{[["Settled","245","green"],["Pending","2","blue"],["Failed","1","red"],["Returned / reversed","0","orange"]].map(x=><button key={x[0]} className={filter===x[0]?"active":""} onClick={()=>setFilter(filter===x[0]?"All":x[0])}><i className={x[2]}/><span>{x[0]}</span><b>{x[1]}</b></button>)}</section><article className="panel recon-table"><div className="recon-head"><span>Reference</span><span>Recipient</span><span>Rail</span><span>Amount</span><span>Status</span><span>Action</span></div>{shown.map(x=><div key={x.id}><span>{x.id}</span><b>{x.name}</b><span>{x.rail}</span><strong>{x.amount}</strong><i className={`status ${x.status.toLowerCase()}`}>{x.status}</i>{x.status==="Failed"?<button onClick={()=>retry(x.id)}><RefreshCw/>Retry failed only</button>:<button onClick={()=>notify(`${x.id} payment trace opened`)}>Trace <ChevronRight/></button>}</div>)}</article></>;
}

export function ApprovalCenter({notify}:{notify:(m:string)=>void}){
  const [status,setStatus]=useState("Pending"),[comment,setComment]=useState("");
  return <><Head eyebrow="MAKER-CHECKER" title="Payroll approval review" copy="Review material changes before signing the locked payroll version." action="Delegate review" onAction={()=>notify("Delegation options opened")}/><section className="approval-review"><article className="panel"><div className="section-heading"><span><ShieldCheck/></span><div><small>PAY-2026-08-V3</small><h2>August 2026 payroll</h2><p>Submitted by James Doe · Locked at 10:00 AM</p></div><i className={`status ${status.toLowerCase()}`}>{status}</i></div><div className="version-compare"><div><small>Previous version</small><b>18,292,400 LRD</b><span>246 employees</span></div><ArrowRight/><div><small>Current version</small><b>18,450,000 LRD</b><span>248 employees</span></div><strong>+157,600 LRD</strong></div><h3>Material changes</h3>{[["2 employees added","+148,400 LRD"],["Exchange rate updated","+18,200 LRD"],["Benefit elections changed","−9,000 LRD"]].map(x=><div className="material-change" key={x[0]}><AlertTriangle/><span>{x[0]}</span><b>{x[1]}</b></div>)}<label>Checker comment<textarea value={comment} onChange={e=>setComment(e.target.value)} placeholder="Add an approval note"/></label><footer><button onClick={()=>{setStatus("Rejected");notify("Payroll returned to maker")}}>Return to maker</button><button className="primary" onClick={()=>{setStatus("Approved");notify("Payroll approved with MFA signature")}}><ShieldCheck/>Approve with MFA</button></footer></article><aside className="panel approval-guard"><h3>Approval safeguards</h3>{["Independent checker","Locked calculation version","MFA transaction signing","Threshold policy satisfied","Complete audit record"].map(x=><p key={x}><CheckCircle2/>{x}</p>)}<div><small>Approval threshold</small><b>Any payroll above 5,000,000 LRD requires two officers.</b></div></aside></section></>;
}

export function LiberiaOperations({notify}:{notify:(m:string)=>void}){
  return <><Head eyebrow="LIBERIA OPERATIONS" title="Country operations center" copy="Statutory deadlines, payment-rail coverage and low-connectivity delivery controls." action="Download country pack" onAction={()=>notify("Liberia country pack prepared")}/><section className="country-grid"><article className="panel"><div className="section-heading"><span><CalendarDays/></span><div><small>FILING CALENDAR</small><h2>Upcoming obligations</h2></div></div>{[["Aug 31","Payroll payment","Ready"],["Sep 10","LRA PAYE remittance","Scheduled"],["Sep 15","NASSCORP contribution","Draft"],["Sep 30","Monthly reconciliation","Upcoming"]].map(x=><button className="country-row" key={x[0]} onClick={()=>notify(`${x[1]} workspace opened`)}><b>{x[0]}</b><span>{x[1]}</span><i>{x[2]}</i><ChevronRight/></button>)}</article><article className="panel"><div className="section-heading"><span><Network/></span><div><small>PAYMENT COVERAGE</small><h2>Provider readiness</h2></div></div>{[["IIPS / NEPS / Pay‑Na Na","Domestic bank and wallet payments","Integration pending"],["Orange Money","Mobile-money salaries","Disabled"],["MTN MoMo","Mobile-money salaries","Disabled"],["PAPSS / Onafriq","Regional disbursements","Certification required"]].map(x=><div className="rail-row" key={x[0]}><Network/><span><b>{x[0]}</b><small>{x[1]}</small></span><i>{x[2]}</i></div>)}</article><article className="panel"><div className="section-heading"><span><MessageSquareText/></span><div><small>LOW CONNECTIVITY</small><h2>Employee delivery</h2></div></div>{[["SMS payslip alerts",true],["Offline payroll pack",true],["Delivery retries",true],["Audio guidance",false]].map(x=><div className="toggle-row" key={String(x[0])}><span>{x[0]}</span><Switch defaultChecked={Boolean(x[1])} onCheckedChange={()=>notify(`${x[0]} preference updated`)}/></div>)}</article><article className="panel"><div className="section-heading"><span><BarChart3/></span><div><small>WORKFORCE FOOTPRINT</small><h2>County reporting</h2></div></div>{[["Montserrado",188,76],["Margibi",28,11],["Bong",19,8],["Nimba",13,5]].map(x=><div className="county-row" key={String(x[0])}><span>{x[0]}</span><Progress value={Number(x[2])}/><b>{x[1]}</b></div>)}</article></section></>;
}

type AIMessage={role:"user"|"assistant";text:string;source?:string};
export function ProspevaAI({notify}:{notify:(m:string)=>void}){
  const [question,setQuestion]=useState(""),[role,setRole]=useState("Payroll Manager"),[scope,setScope]=useState("All operations"),[thinking,setThinking]=useState(false),[completed,setCompleted]=useState<string[]>([]);
  const [messages,setMessages]=useState<AIMessage[]>([{role:"assistant",text:"August payroll is 0.9% higher than July. Two new employees account for most of the increase, while the locked FX-rate change adds 18,200 LRD. Six employees remain blocked by identity, attendance or destination controls.",source:"Locked payroll v4 · six-month employer history"}]);
  const prompts=["Can we request payroll financing?","Explain the payroll increase","Forecast the funding gap","Review ghost employee risks","Check PAYE in LRD"];
  const response=(q:string)=>{const s=q.toLowerCase();if((s.includes("financ")||s.includes("borrow")||s.includes("loan"))&&!s.includes("deduction")&&!s.includes("employee"))return "The locked August payroll has a verified 1,540,000 LRD funding gap. The employer may request financing from an assigned lender using consented KYB, payroll, funding-history, completion and reconciliation evidence. This is not an approval: the lender sets the product, pricing, security and repayment terms, and any approved proceeds must enter the designated payroll funding account.";if(s.includes("ghost")||s.includes("fraud")||s.includes("duplicate"))return "Six employees are held. The strongest signals are one inactive worker reintroduced, one duplicate Orange Money destination and one bank-beneficiary mismatch. Keep all six outside the payment batch until HR verifies employment and an independent Finance approver clears each hold.";if(s.includes("attendance")||s.includes("leave")||s.includes("overtime"))return "Five attendance records need action: two supervisor approvals, one overtime exception, one leave overlap and one missing clock-out. The overtime entry is 3.2× the employee’s six-month average. Resolving these items changes projected gross pay by up to 84,500 LRD.";if(s.includes("fund")||s.includes("balance"))return "The cleared LRD balance is 16,910,000 against an 18,450,000 LRD requirement, leaving a 1,540,000 LRD gap. The employer may add its own cleared funds or separately request assigned-lender financing. Payroll release still requires a funded account and independent approval.";if(s.includes("paye")||s.includes("tax"))return "PAYE is correctly calculated in LRD. Prospeva converted USD taxable earnings at the locked 199.25 LRD/USD rate, combined them with LRD taxable earnings, and calculated a 2,060,000 LRD liability on 20,600,000 LRD-equivalent taxable gross.";if(s.includes("payment")||s.includes("rail")||s.includes("fail"))return "Payment success is 99.2%. One Orange Money instruction failed and can be retried without repeating successful payments. IIPS/NEPS is performing at 99.4%, while Prospeva wallet payments are at 99.9%.";if(s.includes("loan")||s.includes("deduction"))return "Ninety-four of 96 employee payroll-loan deductions are ready. Two exceptions should remain held so successful lender payments are not repeated. These employee deductions are separate from employer payroll financing.";if(s.includes("employee")||s.includes("headcount"))return "There are 248 active employees. Two were added this period, 84 receive mixed-currency pay, 242 are payroll-ready and six remain on integrity holds.";return "I reviewed the current payroll, workforce, attendance, funding, deductions, payments and integrity controls. The highest-priority action is clearing six blocked employee records, followed by funding the 1,540,000 LRD gap before release."};
  const ask=(q:string)=>{const clean=q.trim();if(!clean)return;setMessages(list=>[...list,{role:"user",text:clean}]);setQuestion("");setThinking(true);window.setTimeout(()=>{setMessages(list=>[...list,{role:"assistant",text:response(clean),source:`${scope} · role-aware access for ${role}`}]);setThinking(false)},450)};
  const doAction=(id:string,message:string)=>{setCompleted(list=>list.includes(id)?list:[...list,id]);notify(message)};
  const insights=[
    {id:"ghost",icon:ShieldCheck,label:"INTEGRITY",title:"6 employee records held",copy:"Identity, activity and destination controls prevented release.",action:"Open investigation",message:"Ghost employee investigation queue opened"},
    {id:"funding",icon:CircleDollarSign,label:"FUNDING",title:"1.54M LRD gap",copy:"Cleared funds remain below the total payroll requirement.",action:"Create funding task",message:"Funding task assigned to Finance"},
    {id:"attendance",icon:AlertTriangle,label:"ATTENDANCE",title:"5 records need approval",copy:"Two supervisor approvals and three exceptions remain.",action:"Route to supervisors",message:"Attendance items routed to supervisors"},
    {id:"hr",icon:UserRoundCheck,label:"AUTOMATION",title:"4 cases ready for HR",copy:"Identity cases have the required owner and due date.",action:"Assign to HR",message:"Four cases assigned to HR"},
  ];
  return <><Head eyebrow="PROSPEVAAI" title="Employer intelligence copilot" copy="Analyze authorized payroll and workforce data, explain risks and turn recommendations into controlled tasks." action="Download AI briefing" onAction={()=>notify("ProspevaAI briefing prepared")}/>
    <section className="ai-control-bar"><label>Acting role<Select value={role} onValueChange={setRole}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["Payroll Manager","HR Administrator","Finance Approver","Head of Organization","Supervisor"].map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></label><label>Analysis scope<Select value={scope} onValueChange={setScope}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{["All operations","Payroll","Funding","Payroll financing","Attendance & leave","Compliance","Ghost prevention","Payments"].map(value=><SelectItem key={value} value={value}>{value}</SelectItem>)}</SelectContent></Select></label><span><ShieldCheck/><b>Role-aware access</b><small>ProspevaAI only uses data this role may view.</small></span><button onClick={()=>{setMessages([{role:"assistant",text:"Conversation cleared. What would you like to review?",source:"ProspevaAI secure workspace"}]);notify("ProspevaAI conversation cleared")}}><RefreshCw/>New analysis</button></section>
    <section className="ai-layout ai-expanded"><article className="ai-chat"><div className="ai-brand"><span><Sparkles/></span><div><b>ProspevaAI</b><small>{role} · {scope}</small></div><i>Secure</i></div><div className="ai-thread">{messages.map((message,index)=><div key={index} className={`ai-message ${message.role}`}><span>{message.role==="assistant"?<Bot/>:role.split(" ").map(x=>x[0]).join("")}</span><div><p>{message.text}</p>{message.source&&<small>{message.source}</small>}</div></div>)}{thinking&&<div className="ai-message assistant thinking"><span><Bot/></span><div><i></i><i></i><i></i></div></div>}</div><div className="quick-prompts">{prompts.map(prompt=><button key={prompt} onClick={()=>ask(prompt)}>{prompt}</button>)}</div><form onSubmit={event=>{event.preventDefault();ask(question)}}><input value={question} onChange={event=>setQuestion(event.target.value)} placeholder="Ask about payroll, employees, funding or risk"/><button type="submit" aria-label="Ask ProspevaAI" disabled={thinking||!question.trim()}><Send/></button></form><small className="ai-disclaimer">ProspevaAI supports review; authorized officers remain responsible for payroll and employment decisions.</small></article>
    <aside className="ai-insights ai-action-center"><header><div><Sparkles/><span><small>LIVE RECOMMENDATIONS</small><b>Action center</b></span></div><i>{insights.length-completed.length} open</i></header>{insights.map(item=>{const Icon=item.icon;const done=completed.includes(item.id);return <article key={item.id} className={done?"done":""}><Icon/><div><small>{item.label}</small><b>{item.title}</b><p>{item.copy}</p></div><button onClick={()=>doAction(item.id,item.message)}>{done?<><Check/>Completed</>:<>{item.action}<ChevronRight/></>}</button></article>})}<footer><button onClick={()=>notify("All ProspevaAI recommendations exported")}><Download/>Export recommendations</button></footer></aside></section>
    <section className="ai-data-access"><article className="panel"><div className="section-heading"><span><ShieldCheck/></span><div><small>AUTHORIZED DATA</small><h2>Data ProspevaAI can analyze</h2></div></div>{[["Locked payroll calculations",true],["Employer financing evidence",true],["Funding and payment outcomes",true],["Ghost employee risk signals",true],["Private employee loan purposes",false]].map(row=><div className="toggle-row" key={String(row[0])}><span>{row[0]}</span><Switch defaultChecked={Boolean(row[1])} disabled={!row[1]} onCheckedChange={value=>notify(`${row[0]} ${value?"included":"excluded"}`)}/></div>)}</article><article className="panel"><div className="section-heading"><span><ClipboardCheck/></span><div><small>AI GOVERNANCE</small><h2>Human control remains mandatory</h2></div></div>{["No autonomous payroll approval","No autonomous credit decision","Every created task is audit logged","Sensitive data follows role permissions","Recommendations show the data source"].map(item=><p className="ai-governance-row" key={item}><CheckCircle2/>{item}</p>)}</article></section>
  </>;
}

export function ExecutiveAnalytics({notify}:{notify:(m:string)=>void}){
  const [range,setRange]=useState("6m");
  const bars=[68,74,71,79,83,91];
  return <><Head eyebrow="EXECUTIVE VIEW" title="Payroll performance analytics" copy="Operational scale, payment reliability, statutory processing and employer cost in one view." action="Export board pack" onAction={()=>notify("Executive board pack prepared")}/><div className="analytics-filter"><Select value={range} onValueChange={setRange}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="3m">Last 3 months</SelectItem><SelectItem value="6m">Last 6 months</SelectItem><SelectItem value="12m">Last 12 months</SelectItem></SelectContent></Select></div><section className="kpi-grid">{[["Payroll processed","108.4M LRD","+12.4%"],["On-time payroll","98.7%","+1.2 pts"],["Payment success","99.2%","+0.4 pts"],["Employees served","248","+18"],["Statutory liabilities","22.6M LRD","Current"],["Prospeva fees","684,500 LRD","0.63% take rate"]].map((x,i)=><article key={x[0]}><span>{i%2?<CheckCircle2/>:<WalletCards/>}</span><small>{x[0]}</small><b>{x[1]}</b><em>{x[2]}</em></article>)}</section><section className="analytics-grid"><article className="panel"><div className="section-heading"><span><BarChart3/></span><div><small>{range.toUpperCase()} TREND</small><h2>Payroll volume</h2></div></div><div className="bar-chart">{bars.map((b,i)=><div key={i}><span style={{height:`${b}%`}}/><small>{["Mar","Apr","May","Jun","Jul","Aug"][i]}</small></div>)}</div></article><article className="panel"><div className="section-heading"><span><CircleDollarSign/></span><div><small>CURRENCY MIX</small><h2>Employee net pay</h2></div></div><div className="currency-split"><div><span>LRD</span><b>72%</b></div><div><span>USD</span><b>28%</b></div></div><p className="analytics-note">84 employees receive mixed-currency net pay.</p></article><article className="panel"><div className="section-heading"><span><Network/></span><div><small>RAIL PERFORMANCE</small><h2>Payment success</h2></div></div>{[["Prospeva wallets","99.9%"],["IIPS / NEPS","99.4%"],["Orange Money","98.8%"],["MTN MoMo","97.6%"]].map(x=><div className="metric-row" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b></div>)}</article></section></>;
}
