"use client";

import { useMemo, useState } from "react";
import {
  Activity, AlertTriangle, BadgeCheck, Ban, BookOpen, BriefcaseBusiness, Building2, CalendarDays, Check, ClipboardCheck,
  CheckCircle2, ChevronRight, Clock3, Cloud, Database, Download, Eye,
  FileText, Fingerprint, FolderOpen, GraduationCap, Link2, LockKeyhole, Mail,
  MessageSquare, RefreshCw, Search, Settings2, ShieldCheck, Upload,
  UserCheck, UserPlus, Users, WalletCards, X,
} from "lucide-react";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Switch } from "@/components/ui/switch";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const roleDefinitions = [
  { name: "Chief Executive Officer", icon: Building2, copy: "Company-wide workforce oversight, final approval and emergency authority.", tone: "purple" },
  { name: "General Manager", icon: BriefcaseBusiness, copy: "Hiring, transfers, promotions, delegations and departmental access.", tone: "blue" },
  { name: "Operations Manager", icon: Settings2, copy: "Operational staffing, supervisors, responsibilities and workload coverage.", tone: "teal" },
  { name: "HR Administrator", icon: Users, copy: "Employee records, contracts, leave policies and people reports.", tone: "blue" },
  { name: "Finance Approver", icon: WalletCards, copy: "Funding, deductions, bank files, reconciliation and payment approval.", tone: "green" },
  { name: "Head of Organization", icon: Building2, copy: "Executive visibility and final approval for company, NGO or university.", tone: "purple" },
  { name: "Payroll Manager", icon: Database, copy: "Calculate payroll, resolve exceptions and submit the locked payroll version.", tone: "orange" },
  { name: "Supervisor", icon: UserCheck, copy: "Approve leave and attendance for assigned teams before payroll cutoff.", tone: "teal" },
];

const people = [
  { id: "USR-001", name: "James Doe", email: "james@monroviabusiness.lr", role: "Operations Manager", scope: "All employees", department: "Operations", mfa: true },
  { id: "USR-002", name: "Martha Kallon", email: "martha@monroviabusiness.lr", role: "Finance Approver", scope: "Organization-wide", department: "Finance", mfa: true },
  { id: "USR-003", name: "Hawa Sirleaf", email: "hawa@monroviabusiness.lr", role: "HR Administrator", scope: "Organization-wide", department: "People", mfa: true },
  { id: "USR-004", name: "Samuel Toe", email: "samuel@monroviabusiness.lr", role: "Supervisor", scope: "Sales department", department: "Sales", mfa: true },
  { id: "USR-005", name: "Dr. Fatu Brown", email: "fatu@monroviabusiness.lr", role: "Chief Executive Officer", scope: "Organization-wide", department: "Executive", mfa: true },
  { id: "USR-006", name: "Kelvin Freeman", email: "kelvin@monroviabusiness.lr", role: "Supervisor", scope: "Operations department", department: "Operations", mfa: false },
  { id: "USR-007", name: "Moses Cole", email: "moses@monroviabusiness.lr", role: "General Manager", scope: "Organization-wide", department: "Executive", mfa: true },
];

const permissions = [
  ["Employee records", true, true, true, true, false, true, true, true],
  ["Assign responsibilities", true, true, true, true, false, true, false, false],
  ["Promote or transfer", true, true, true, true, false, true, false, false],
  ["Suspend or offboard", true, true, true, false, false, true, false, false],
  ["Approve leave", true, true, true, true, false, true, false, true],
  ["Approve attendance", true, true, true, true, false, true, true, true],
  ["Calculate payroll", false, false, false, false, false, false, true, false],
  ["Approve payroll", true, true, false, false, true, true, false, false],
  ["Release funds", true, false, false, false, true, true, false, false],
  ["Executive analytics", true, true, true, false, true, true, false, false],
];

export function PeopleRoles({notify}:{notify:(message:string)=>void}) {
  const [selected, setSelected] = useState(people[3]);
  const [role, setRole] = useState(selected.role);
  const [scope, setScope] = useState(selected.scope);
  const [organization, setOrganization] = useState("company");
  const [query, setQuery] = useState("");
  const [workflow, setWorkflow] = useState<string|null>(null);
  const filtered = people.filter(person => `${person.name} ${person.email} ${person.role}`.toLowerCase().includes(query.toLowerCase()));
  const choose = (person:typeof people[number]) => { setSelected(person); setRole(person.role); setScope(person.scope); };
  return <>
    <header className="page-head"><div><span>ACCESS & ACCOUNTABILITY</span><h1>People, roles & responsibilities</h1><p>Manage staff lifecycle and give each officer only the authority required for their job.</p></div><button className="primary compact" onClick={()=>setWorkflow("Add & onboard staff")}><UserPlus/>Add staff member</button></header>
    <section className="executive-command">
      <header><div><small>AUTHORIZED WORKFORCE ADMINISTRATION</small><h2>Executive access command</h2><p>Senior executives can manage staff within approved authority, country and department scope.</p></div><span><ShieldCheck/>Maker-checker enforced</span></header>
      <div className="executive-authority">{roleDefinitions.slice(0,3).map(item=>{const Icon=item.icon;return <article key={item.name}><Icon/><div><b>{item.name}</b><small>{item.copy}</small></div></article>})}</div>
      <div className="staff-lifecycle">{[
        ["Add & onboard staff","Create identity, position and reporting line",UserPlus],
        ["Assign responsibility","Set owner, scope, priority and escalation",ClipboardCheck],
        ["Promote or transfer","Remove obsolete access before adding new",RefreshCw],
        ["Temporary delegation","Time-limited acting authority and limits",Clock3],
        ["Suspend or offboard","Revoke access and preserve audit history",Ban],
      ].map(([label,copy,Icon]:any)=><button key={label} onClick={()=>setWorkflow(label)} className={label.includes("offboard")?"danger":""}><Icon/><b>{label}</b><small>{copy}</small></button>)}</div>
      <footer><b>Permission model</b><span>Resource</span><i>+</i><span>Action</span><i>+</i><span>Scope</span><small>Support Cases + Update + Assigned Liberia cases</small></footer>
    </section>
    <section className="role-summary">
      <article><span><Users/></span><div><small>Portal users</small><b>18</b><em>16 active · 2 invited</em></div></article>
      <article><span><UserCheck/></span><div><small>Supervisors</small><b>7</b><em>184 employees assigned</em></div></article>
      <article><span><ShieldCheck/></span><div><small>MFA coverage</small><b>94%</b><em>1 officer needs setup</em></div></article>
      <article><span><LockKeyhole/></span><div><small>Conflicting access</small><b>0</b><em>Maker-checker enforced</em></div></article>
    </section>
    <section className="roles-layout">
      <article className="panel people-directory">
        <div className="panel-title"><div><Users/><h2>Authorized people</h2></div></div>
        <div className="role-search"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search a person or role"/></div>
        {filtered.map(person=><button key={person.id} className={selected.id===person.id?"selected":""} onClick={()=>choose(person)}>
          <span className="avatar">{person.name.split(" ").map(part=>part[0]).join("")}</span><div><b>{person.name}</b><small>{person.role} · {person.department}</small></div>{person.mfa?<BadgeCheck/>:<AlertTriangle/>}<ChevronRight/>
        </button>)}
      </article>
      <article className="panel role-editor">
        <div className="role-editor-head"><span className="avatar xl">{selected.name.split(" ").map(part=>part[0]).join("")}</span><div><small>{selected.id}</small><h2>{selected.name}</h2><p>{selected.email}</p></div><i>{selected.mfa?"MFA verified":"MFA required"}</i></div>
        <div className="role-form-grid">
          <label>Organization type<Select value={organization} onValueChange={setOrganization}><SelectTrigger className="sheet-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="company">Company</SelectItem><SelectItem value="university">University or school</SelectItem><SelectItem value="ngo">NGO or foundation</SelectItem><SelectItem value="hospital">Hospital or clinic</SelectItem><SelectItem value="church">Church or faith organization</SelectItem></SelectContent></Select></label>
          <label>Portal role<Select value={role} onValueChange={setRole}><SelectTrigger className="sheet-select"><SelectValue/></SelectTrigger><SelectContent>{roleDefinitions.map(item=><SelectItem key={item.name} value={item.name}>{item.name}</SelectItem>)}</SelectContent></Select></label>
          <label>Access scope<Select value={scope} onValueChange={setScope}><SelectTrigger className="sheet-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="Organization-wide">Organization-wide</SelectItem><SelectItem value="All employees">All employees</SelectItem><SelectItem value="Sales department">Sales department</SelectItem><SelectItem value="Operations department">Operations department</SelectItem><SelectItem value="Direct reports only">Direct reports only</SelectItem><SelectItem value="University faculty only">University faculty only</SelectItem></SelectContent></Select></label>
          <label>Approval limit<Select defaultValue="5m"><SelectTrigger className="sheet-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="none">No payment approval</SelectItem><SelectItem value="500k">Up to 500,000 LRD</SelectItem><SelectItem value="5m">Up to 5,000,000 LRD</SelectItem><SelectItem value="unlimited">Organization policy limit</SelectItem></SelectContent></Select></label>
        </div>
        <div className="permission-toggles">
          <h3>Additional controls</h3>
          <div><span><b>Approve leave</b><small>Annual, sick, parental, study and other configured leave</small></span><Switch defaultChecked={role==="Supervisor"||role==="HR Administrator"} onCheckedChange={value=>notify(`Leave approval permission ${value?"enabled":"disabled"}`)}/></div>
          <div><span><b>Approve attendance for payroll</b><small>Sign off hours, overtime and exceptions for assigned teams</small></span><Switch defaultChecked={role==="Supervisor"||role==="HR Administrator"} onCheckedChange={value=>notify(`Attendance approval permission ${value?"enabled":"disabled"}`)}/></div>
          <div><span><b>Access employee documents</b><small>Files remain governed by SharePoint and Prospeva permissions</small></span><Switch defaultChecked={role==="HR Administrator"} onCheckedChange={value=>notify(`Employee document access ${value?"enabled":"disabled"}`)}/></div>
        </div>
        <aside className="sod-guard"><ShieldCheck/><div><b>Separation of duties is active</b><p>A payroll maker cannot be its final checker. Funding release requires Finance or Head of Organization approval.</p></div></aside>
        <footer className="role-actions"><button onClick={()=>notify("Role changes discarded")}>Discard</button><button className="primary compact" onClick={()=>notify(`${role} access assigned to ${selected.name}`)}><Check/>Assign role</button></footer>
      </article>
    </section>
    <section className="role-cards">{roleDefinitions.map(item=>{const Icon=item.icon;return <article className="panel" key={item.name}><span className={item.tone}><Icon/></span><div><h3>{item.name}</h3><p>{item.copy}</p><small>{people.filter(person=>person.role===item.name).length} assigned</small></div><button onClick={()=>notify(`${item.name} permissions opened`)}>Review <ChevronRight/></button></article>})}</section>
    <article className="panel permission-matrix"><div className="panel-title"><div><ShieldCheck/><h2>Permission matrix</h2></div><button onClick={()=>notify("Permission matrix exported")}>Export matrix <Download/></button></div><div className="matrix-scroll"><table><thead><tr><th>Capability</th>{roleDefinitions.map(role=><th key={role.name}>{role.name.replace("Chief Executive Officer","CEO").replace("General Manager","GM").replace("Operations Manager","Ops Manager").replace(" Administrator","").replace(" of Organization","")}</th>)}</tr></thead><tbody>{permissions.map(row=><tr key={String(row[0])}><td>{row[0]}</td>{roleDefinitions.map((_,index)=>{const allowed=row[index+1];return <td key={index}>{allowed?<CheckCircle2/>:<span>—</span>}</td>})}</tr>)}</tbody></table></div></article>
    <Dialog open={Boolean(workflow)} onOpenChange={open=>!open&&setWorkflow(null)}><DialogContent className="staff-workflow-dialog"><DialogHeader><DialogTitle>{workflow}</DialogTitle><DialogDescription>This prototype creates a governed workforce action and immutable audit record.</DialogDescription></DialogHeader><div className="staff-workflow-form"><label>Staff member<input placeholder="Search or enter staff name"/></label><label>Position<Select defaultValue="customer"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="customer">Customer Service Representative</SelectItem><SelectItem value="it">IT Officer</SelectItem><SelectItem value="cyber">Cybersecurity Specialist</SelectItem><SelectItem value="marketing">Marketing Officer</SelectItem><SelectItem value="manager">Operations Manager</SelectItem></SelectContent></Select></label><label>Reports to<Select defaultValue="ops"><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="ceo">Chief Executive Officer</SelectItem><SelectItem value="gm">General Manager</SelectItem><SelectItem value="ops">Operations Manager</SelectItem></SelectContent></Select></label><label>Effective date<input type="date" defaultValue="2026-09-21"/></label><label className="wide">Reason / responsibility<textarea placeholder="Describe the responsibility, employment change or access reason"/></label></div><aside className="sod-guard"><ShieldCheck/><div><b>Independent approval required</b><p>Privileged access, financial authority and termination cannot be self-approved. Former staff records remain in the audit history.</p></div></aside><DialogFooter><button onClick={()=>setWorkflow(null)}>Cancel</button><button className="primary compact" onClick={()=>{notify(`${workflow} request submitted for approval`);setWorkflow(null)}}>Submit for approval</button></DialogFooter></DialogContent></Dialog>
  </>;
}

type LeaveRequest = {id:string;name:string;team:string;type:string;dates:string;days:string;balance:string;coverage:string;impact:string;status:"Pending"|"Approved"|"Returned"|"Declined"};
const initialLeave:LeaveRequest[] = [
  {id:"LEV-2041",name:"Hawa Sirleaf",team:"People",type:"Annual leave",dates:"Sep 14–18, 2026",days:"5 days",balance:"13 days after",coverage:"Fatu Brown",impact:"No payroll impact",status:"Pending"},
  {id:"LEV-2042",name:"Kelvin Freeman",team:"Operations",type:"Sick leave",dates:"Sep 8–10, 2026",days:"3 days",balance:"Medical note attached",coverage:"Samuel Toe",impact:"Paid leave",status:"Pending"},
  {id:"LEV-2043",name:"Martha Kallon",team:"Finance",type:"Study leave",dates:"Sep 21–25, 2026",days:"5 days",balance:"2 days paid · 3 unpaid",coverage:"James Doe",impact:"18,600 LRD deduction",status:"Pending"},
];
const attendanceRows = [
  {id:"ATT-271",name:"Samuel Toe",team:"Sales",period:"Aug 16–31",regular:"88.0",overtime:"4.0",exceptions:"0",status:"Ready"},
  {id:"ATT-272",name:"Kelvin Freeman",team:"Operations",period:"Aug 16–31",regular:"80.0",overtime:"3.5",exceptions:"1",status:"Review"},
  {id:"ATT-273",name:"Hawa Sirleaf",team:"People",period:"Aug 16–31",regular:"84.0",overtime:"0.0",exceptions:"0",status:"Ready"},
  {id:"ATT-274",name:"Martha Kallon",team:"Finance",period:"Aug 16–31",regular:"82.0",overtime:"2.0",exceptions:"1",status:"Review"},
];
const mobileWorkEvents = [
  {employee:"Kelvin Freeman",event:"Clocked in",time:"8:03 AM",place:"Monrovia HQ",device:"Prospeva Personal · iPhone",status:"Synced"},
  {employee:"Hawa Sirleaf",event:"Clocked in",time:"7:58 AM",place:"Congo Town",device:"Prospeva Personal · Android",status:"Synced"},
  {employee:"Samuel Toe",event:"Clocked in",time:"8:24 AM",place:"Monrovia HQ",device:"Prospeva Personal · Android",status:"Review"},
  {employee:"Martha Kallon",event:"Clocked out",time:"Yesterday · 5:06 PM",place:"Monrovia HQ",device:"Prospeva Personal · iPhone",status:"Synced"},
];

export function LeaveAttendanceHub({notify}:{notify:(message:string)=>void}) {
  const [tab,setTab] = useState<"leave"|"balances"|"policy"|"attendance"|"readiness">("leave");
  const [leave,setLeave] = useState(initialLeave);
  const [selected,setSelected] = useState<string[]>(attendanceRows.filter(row=>row.status==="Ready").map(row=>row.id));
  const [balanceEmployee,setBalanceEmployee] = useState("Kelvin Freeman");
  const [policies,setPolicies] = useState([
    {category:"Annual / vacation",legal:15,policy:20,unit:"days",used:8,pending:5,note:"4 years’ service · statutory 3 workweeks"},
    {category:"Sick",legal:10,policy:12,unit:"days",used:2,pending:0,note:"Statutory balance accumulates during service"},
    {category:"Family care",legal:5,policy:5,unit:"days",used:1,pending:0,note:"Paid · does not accumulate"},
    {category:"Bereavement",legal:5,policy:5,unit:"days",used:0,pending:0,note:"Paid · does not accumulate"},
    {category:"Personal",legal:0,policy:3,unit:"days",used:1,pending:0,note:"Employer-provided category"},
    {category:"Maternity",legal:14,policy:14,unit:"weeks",used:0,pending:0,note:"Paid · event-based entitlement"},
    {category:"Paternity",legal:5,policy:5,unit:"days",used:0,pending:0,note:"Law: unpaid · employer policy: paid"},
  ]);
  const updatePolicy=(index:number,delta:number)=>setPolicies(rows=>rows.map((row,i)=>i===index?{...row,policy:Math.max(row.legal,row.policy+delta)}:row));
  const decide = (id:string,status:LeaveRequest["status"]) => { setLeave(rows=>rows.map(row=>row.id===id?{...row,status}:row)); notify(`Leave request ${status.toLowerCase()}`); };
  const approved = leave.filter(request=>request.status==="Approved").length;
  return <>
    <header className="page-head"><div><span>SUPERVISOR WORKSPACE</span><h1>Leave & attendance approvals</h1><p>Prototype clock events and leave requests demonstrate the future shared-record workflow.</p></div><button className="sync-control" onClick={()=>notify("Prototype activity refreshed")}><RefreshCw/><span><b>Prototype sync preview</b><small>Demo records only</small></span></button></header>
    <section className="mini-stats"><article className="stat"><span className="orange"><CalendarDays/></span><small>Leave awaiting review</small><b>{leave.filter(row=>row.status==="Pending").length}</b><em>Across 3 departments</em></article><article className="stat"><span className="blue"><Clock3/></span><small>Timesheets ready</small><b>242 of 248</b><em>6 need attention</em></article><article className="stat"><span className="green"><UserCheck/></span><small>Supervisor approval</small><b>97.6%</b><em>{approved} leave approved today</em></article><article className="stat"><span className="purple"><WalletCards/></span><small>Payroll impact</small><b>84,500 LRD</b><em>Leave + overtime adjustments</em></article></section>
    <div className="workspace-tabs" role="tablist"><button className={tab==="leave"?"active":""} onClick={()=>setTab("leave")}><CalendarDays/>Leave requests <i>{leave.filter(row=>row.status==="Pending").length}</i></button><button className={tab==="balances"?"active":""} onClick={()=>setTab("balances")}><WalletCards/>Leave balances</button><button className={tab==="policy"?"active":""} onClick={()=>setTab("policy")}><BookOpen/>Policy settings</button><button className={tab==="attendance"?"active":""} onClick={()=>setTab("attendance")}><Clock3/>Attendance approval <i>6</i></button><button className={tab==="readiness"?"active":""} onClick={()=>setTab("readiness")}><ShieldCheck/>Payroll readiness</button></div>
    {tab==="leave"&&<section className="leave-layout"><article className="panel leave-queue"><div className="panel-title"><div><CalendarDays/><h2>Requests requiring action</h2></div><Select defaultValue="all"><SelectTrigger className="mini-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="all">All leave types</SelectItem><SelectItem value="annual">Annual leave</SelectItem><SelectItem value="sick">Sick leave</SelectItem><SelectItem value="parental">Maternity & paternity</SelectItem><SelectItem value="study">Study leave</SelectItem><SelectItem value="bereavement">Bereavement</SelectItem><SelectItem value="unpaid">Unpaid leave</SelectItem></SelectContent></Select></div>{leave.map(request=><article key={request.id} className={`leave-request ${request.status.toLowerCase()}`}><header><span className="avatar">{request.name.split(" ").map(part=>part[0]).join("")}</span><div><small>{request.id} · {request.team}</small><b>{request.name}</b><p>{request.type} · {request.dates}</p></div><i>{request.status}</i></header><div className="leave-facts"><span><small>Duration</small><b>{request.days}</b></span><span><small>Balance / evidence</small><b>{request.balance}</b></span><span><small>Work coverage</small><b>{request.coverage}</b></span><span><small>Payroll impact</small><b>{request.impact}</b></span></div>{request.status==="Pending"&&<footer><button onClick={()=>decide(request.id,"Declined")}><X/>Decline</button><button onClick={()=>decide(request.id,"Returned")}><RefreshCw/>Return for details</button><button className="primary compact" onClick={()=>decide(request.id,"Approved")}><Check/>Approve leave</button></footer>}</article>)}</article><aside className="panel leave-policy"><div className="panel-title"><div><BookOpen/><h2>Leave policy guide</h2></div></div>{[["Annual leave","20 days · service-based legal floor"],["Sick leave","12 days · 10-day legal floor"],["Family-care leave","5 paid days"],["Maternity leave","14 paid weeks · HR verification"],["Paternity leave","5 days · employer policy pays"],["Personal leave","3 days · employer benefit"],["Bereavement","5 paid days"],["Unpaid leave","HR + Finance approval"]].map(row=><button key={row[0]} onClick={()=>notify(`${row[0]} policy opened`)}><span><b>{row[0]}</b><small>{row[1]}</small></span><ChevronRight/></button>)}<aside><ShieldCheck/><p>Prospeva checks statutory minimums, policy balances, overlapping dates, evidence, coverage and payroll impact before approval.</p></aside></aside></section>}
    {tab==="balances"&&<section className="leave-balance-workspace"><article className="panel"><div className="panel-title"><div><WalletCards/><h2>Employee leave schedule</h2></div><Select value={balanceEmployee} onValueChange={setBalanceEmployee}><SelectTrigger className="balance-employee-select"><SelectValue/></SelectTrigger><SelectContent>{["Kelvin Freeman","Hawa Sirleaf","Martha Kallon","Samuel Toe"].map(name=><SelectItem key={name} value={name}>{name}</SelectItem>)}</SelectContent></Select></div><div className="employee-balance-hero"><span className="avatar xl">{balanceEmployee.split(" ").map(part=>part[0]).join("")}</span><div><small>2026 LEAVE YEAR · EMP-0248</small><h2>{balanceEmployee}</h2><p>Full-time · 8 hours/day · 5-day workweek · 4 years continuous service</p></div><i><ShieldCheck/>Policy + legal floor applied</i></div><div className="leave-balance-table"><div className="leave-balance-row heading"><b>Leave category</b><b>Annual entitlement</b><b>Used</b><b>Pending</b><b>Available</b></div>{policies.map(row=>{const available=Math.max(0,row.policy-row.used-row.pending);return <div className="leave-balance-row" key={row.category}><span><b>{row.category}</b><small>{row.note}</small></span><span><b>{row.policy} {row.unit}</b><small>{row.unit==="days"?`${row.policy*8} hours`:"Event-based"}</small></span><span>{row.used} {row.unit}</span><span>{row.pending} {row.unit}</span><em>{row.category==="Maternity"||row.category==="Paternity"?"Event-based":`${available} ${row.unit}${row.unit==="days"?` · ${available*8} hrs`:""}`}</em></div>})}</div></article><aside className="balance-rules"><article className="panel"><ShieldCheck/><div><h3>Entitlement engine</h3><p>Prospeva compares the employee’s statutory entitlement with the employer policy and grants the more favorable amount.</p></div></article><article className="panel"><CalendarDays/><div><h3>Service-based annual leave</h3><p>Annual leave recalculates when the employee reaches a statutory continuous-service milestone.</p></div></article><article className="panel"><FileText/><div><h3>Five-year records</h3><p>Leave granted and remuneration records remain available to the employee and authorized reviewers.</p></div></article></aside></section>}
    {tab==="policy"&&<section className="policy-settings-workspace"><article className="panel"><div className="panel-title"><div><BookOpen/><h2>Employer leave policy</h2></div><i className="legal-guard"><ShieldCheck/>Legal floor locked</i></div><div className="policy-setting-table"><div className="policy-setting-row heading"><b>Category</b><b>Decent Work Act minimum</b><b>Employer policy</b><b>Effective entitlement</b></div>{policies.map((row,index)=><div className="policy-setting-row" key={row.category}><span><b>{row.category}</b><small>{row.note}</small></span><span>{row.legal?`${row.legal} ${row.unit}`:"No statutory bank"}</span><div className="policy-stepper"><button onClick={()=>{updatePolicy(index,-1);notify("Policy cannot be reduced below the legal minimum")}}>−</button><b>{row.policy} {row.unit}</b><button onClick={()=>updatePolicy(index,1)}>+</button></div><em>{Math.max(row.legal,row.policy)} {row.unit}</em></div>)}</div><footer className="policy-save"><div><FileText/><span><b>Liberia Decent Work Act, 2015</b><small>Annual leave §§18.1–18.5 · Personal leave §§19.2–19.5 · Maternity and paternity §§20.1–20.6</small></span></div><button className="primary compact" onClick={()=>notify("Leave policy saved with effective date, approver and audit record")}><Check/>Save & publish policy</button></footer></article><aside className="policy-warning"><AlertTriangle/><div><b>Policy changes require controlled publication</b><p>Increases may take effect immediately. Reductions cannot affect accrued entitlements or fall below the applicable statutory minimum. Material changes should require HR preparation and independent approval.</p></div></aside></section>}
    {tab==="attendance"&&<section className="attendance-sync-stack"><aside className="personal-sync-banner"><Fingerprint/><div><small>AUTHORITATIVE ATTENDANCE SOURCE</small><h2>Prospeva Personal account</h2><p>Employees clock in, clock out and request leave in Mobile → More → Work & Leave. Device, location and timestamp are verified and synchronized automatically.</p></div><i><RefreshCw/>Live</i></aside><article className="panel mobile-event-feed"><div className="panel-title"><div><Activity/><h2>Live employee activity</h2></div><button onClick={()=>notify("Personal-account activity refreshed")}><RefreshCw/>Refresh</button></div>{mobileWorkEvents.map(row=><button key={row.employee+row.time} onClick={()=>notify(`${row.employee} verified work event opened`)}><span className="avatar">{row.employee.split(" ").map(x=>x[0]).join("")}</span><div><b>{row.employee} · {row.event}</b><small>{row.time} · {row.place}</small><em>{row.device}</em></div><i className={row.status.toLowerCase()}>{row.status}</i><ChevronRight/></button>)}</article><article className="panel attendance-approval"><div className="panel-title"><div><Clock3/><h2>Synced direct-report timesheets</h2></div><button onClick={()=>notify("Attendance register exported")}>Export <Download/></button></div><div className="attendance-tools"><label><input type="checkbox" checked={selected.length===attendanceRows.length} onChange={event=>setSelected(event.target.checked?attendanceRows.map(row=>row.id):[])}/>Select all</label><span>Source: verified Personal accounts · Cutoff Aug 28, 5:00 PM</span><button className="primary compact" disabled={!selected.length} onClick={()=>{notify(`${selected.length} synced timesheets approved for payroll`);setSelected([])}}><Check/>Approve selected for payroll</button></div><div className="attendance-table"><div className="attendance-head"><span></span><span>Employee</span><span>Period</span><span>Regular</span><span>Overtime</span><span>Exceptions</span><span>Status</span><span></span></div>{attendanceRows.map(row=><div key={row.id}><input type="checkbox" checked={selected.includes(row.id)} onChange={event=>setSelected(list=>event.target.checked?[...list,row.id]:list.filter(id=>id!==row.id))}/><span><b>{row.name}</b><small>{row.team} · {row.id}</small></span><span>{row.period}</span><span>{row.regular} hrs</span><span>{row.overtime} hrs</span><span className={row.exceptions==="0"?"ok":"warn"}>{row.exceptions}</span><i className={row.status.toLowerCase()}>{row.status}</i><button onClick={()=>notify(`${row.name} attendance detail opened`)}><ChevronRight/></button></div>)}</div><aside className="approval-note"><ShieldCheck/><span><b>Supervisor attestation—not data entry</b><p>Supervisors approve synchronized records for payroll. A correction requires a reason, supporting evidence and an immutable audit entry; it never silently overwrites the employee event.</p></span></aside></article></section>}
    {tab==="readiness"&&<section className="readiness-grid"><article className="panel readiness-score"><span><b>97.6%</b><small>attendance approved</small></span><div><h2>Payroll readiness</h2><p>242 employees are approved. Resolve six remaining records before calculation.</p><button className="primary compact" onClick={()=>setTab("attendance")}>Review 6 records <ChevronRight/></button></div></article><article className="panel"><div className="panel-title"><div><AlertTriangle/><h2>Blocking items</h2></div></div>{[["2","Missing supervisor approval"],["2","Overtime above department limit"],["1","Leave overlaps attendance"],["1","Missing clock-out"]].map(row=><div className="blocker-row" key={row[1]}><b>{row[0]}</b><span>{row[1]}</span><button onClick={()=>setTab("attendance")}>Resolve</button></div>)}</article><article className="panel"><div className="panel-title"><div><ShieldCheck/><h2>Approval chain</h2></div></div>{[["Supervisor","Team attendance","In progress"],["HR Administrator","Policy & leave review","Pending"],["Payroll Manager","Import locked records","Pending"]].map((row,index)=><div className="chain-row" key={row[0]}><i>{index+1}</i><span><b>{row[0]}</b><small>{row[1]}</small></span><em>{row[2]}</em></div>)}</article></section>}
  </>;
}

const microsoftProducts = [
  {id:"sharepoint",name:"SharePoint",icon:FolderOpen,copy:"Employee files, policies and controlled document libraries."},
  {id:"onedrive",name:"OneDrive",icon:Cloud,copy:"Secure working documents and approved payroll exports."},
  {id:"teams",name:"Microsoft Teams",icon:MessageSquare,copy:"Approval cards, deadline reminders and exception alerts."},
  {id:"outlook",name:"Outlook",icon:Mail,copy:"Leave calendars, payroll cutoffs and approval notifications."},
];

export function MicrosoftCenter({notify}:{notify:(message:string)=>void}) {
  const [connected,setConnected] = useState<string[]>([]);
  const [provider,setProvider] = useState<"prospera"|"sharepoint">("prospera");
  const [syncing,setSyncing] = useState(false);
  const connect = (id:string,name:string) => {setConnected(list=>list.includes(id)?list.filter(item=>item!==id):[...list,id]);notify(`${name} ${connected.includes(id)?"disconnected":"connected for demonstration"}`)};
  const synced = connected.includes("sharepoint");
  return <>
    <header className="page-head"><div><span>CONNECTED WORKPLACE</span><h1>Microsoft 365 integration</h1><p>Connect Prospeva workflows to the Microsoft tools your organization already uses.</p></div><button className="primary compact" onClick={()=>notify("Microsoft administrator consent opened")}><Link2/>Connect Microsoft 365</button></header>
    <section className="microsoft-hero"><div className="ms-mark"><i></i><i></i><i></i><i></i></div><div><small>MICROSOFT 365 FOR PROSPEVA</small><h2>Employee files and approvals, connected securely.</h2><p>Keep payroll authority in Prospeva while SharePoint governs documents and Teams or Outlook delivers work notifications.</p></div><span className={connected.length?"connected":""}><ShieldCheck/>{connected.length?`${connected.length} services connected`:"Administrator consent required"}</span></section>
    <section className="integration-cards">{microsoftProducts.map(product=>{const Icon=product.icon;const active=connected.includes(product.id);return <article className="panel" key={product.id}><header><span><Icon/></span><i className={active?"active":""}>{active?"Connected":"Available"}</i></header><h3>{product.name}</h3><p>{product.copy}</p><button className={active?"connected":""} onClick={()=>connect(product.id,product.name)}>{active?<><Check/>Connected</>:<><Link2/>Connect</>}</button></article>})}</section>
    <section className="sharepoint-layout">
      <article className="panel sharepoint-config"><div className="panel-title"><div><FolderOpen/><h2>Employee document system</h2></div><i className={synced?"status ready":"status exception"}>{synced?"SharePoint ready":"Setup required"}</i></div>
        <div className="document-provider"><button className={provider==="prospera"?"active":""} onClick={()=>setProvider("prospera")}><Database/><span><b>Prospeva files</b><small>Use Prospeva’s employee document workspace</small></span></button><button className={provider==="sharepoint"?"active":""} onClick={()=>setProvider("sharepoint")}><FolderOpen/><span><b>SharePoint</b><small>Use your Microsoft document library</small></span></button></div>
        {provider==="sharepoint"&&<div className="sharepoint-form"><label>SharePoint site<input defaultValue="https://monroviabusiness.sharepoint.com/sites/people"/></label><label>Document library<Select defaultValue="employees"><SelectTrigger className="sheet-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="employees">Employee Records</SelectItem><SelectItem value="hr">HR Documents</SelectItem><SelectItem value="payroll">Payroll Evidence</SelectItem></SelectContent></Select></label><label>Folder structure<Select defaultValue="id"><SelectTrigger className="sheet-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="id">Employee ID / Document type</SelectItem><SelectItem value="department">Department / Employee</SelectItem><SelectItem value="year">Year / Employee / Type</SelectItem></SelectContent></Select></label><label>Sync behavior<Select defaultValue="reference"><SelectTrigger className="sheet-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="reference">Store secure SharePoint references</SelectItem><SelectItem value="copy">Copy approved documents to Prospeva</SelectItem><SelectItem value="upload">Upload new documents to SharePoint</SelectItem></SelectContent></Select></label></div>}
        <aside className="data-boundary"><LockKeyhole/><span><b>Your organization keeps document control</b><p>Prospeva stores the file reference and approved metadata. Microsoft permissions, retention labels and access policies remain authoritative.</p></span></aside>
        <footer className="role-actions"><button onClick={()=>notify("SharePoint mapping preview opened")}><Eye/>Preview mapping</button><button className="primary compact" disabled={provider==="sharepoint"&&!synced} onClick={()=>notify("Employee document configuration saved")}><Check/>Save configuration</button></footer>
      </article>
      <article className="panel metadata-map"><div className="panel-title"><div><Settings2/><h2>SharePoint metadata map</h2></div></div>{[["Prospeva employee ID","EmployeeID","Required"],["Legal name","EmployeeName","Required"],["Department","Department","Synced"],["Document type","DocumentType","Required"],["Expiration date","ExpiryDate","Optional"],["Verification status","ProspevaStatus","Synced"]].map(row=><div key={row[0]}><span><b>{row[0]}</b><small>{row[1]}</small></span><i>{row[2]}</i><CheckCircle2/></div>)}<button onClick={()=>notify("SharePoint column mapping opened")}><Settings2/>Edit column mapping</button></article>
    </section>
    <section className="microsoft-workflows">
      <article className="panel"><div className="panel-title"><div><MessageSquare/><h2>Teams approval notifications</h2></div></div>{[["Leave approval cards","Send to employee’s assigned supervisor"],["Attendance cutoff reminders","Send 24 and 4 hours before cutoff"],["Payroll approval request","Send to Finance and Head of Organization"],["Funding exceptions","Alert Finance when cleared funds are low"]].map(row=><div className="workflow-toggle" key={row[0]}><span><b>{row[0]}</b><small>{row[1]}</small></span><Switch defaultChecked onCheckedChange={value=>notify(`${row[0]} ${value?"enabled":"disabled"}`)}/></div>)}</article>
      <article className="panel"><div className="panel-title"><div><CalendarDays/><h2>Outlook calendar sync</h2></div></div>{[["Approved employee leave","Team leave calendar"],["Payroll cutoff","Payroll operations calendar"],["Pay date","Organization calendar"],["Statutory filing dates","Finance compliance calendar"]].map(row=><div className="workflow-toggle" key={row[0]}><span><b>{row[0]}</b><small>{row[1]}</small></span><Switch defaultChecked={row[0]!=="Pay date"} onCheckedChange={value=>notify(`${row[0]} calendar sync ${value?"enabled":"disabled"}`)}/></div>)}</article>
      <article className="panel sync-audit"><div className="panel-title"><div><RefreshCw/><h2>Connection health</h2></div></div><div><span>Last directory sync</span><b>{syncing?"Syncing now…":"Today · 9:32 AM"}</b></div><div><span>Employees matched</span><b>246 of 248</b></div><div><span>File links healthy</span><b>1,842</b></div><div><span>Permission conflicts</span><b className="orange-text">2 to review</b></div><button disabled={syncing} onClick={()=>{setSyncing(true);window.setTimeout(()=>{setSyncing(false);notify("Microsoft directory sync completed")},900)}}><RefreshCw className={syncing?"spin":""}/>Run sync now</button></article>
    </section>
    <aside className="admin-consent"><ShieldCheck/><div><b>Microsoft 365 administrator action</b><p>A tenant administrator must approve Prospeva’s requested permissions. Prospeva should use least-privilege Microsoft Graph scopes, encrypt tokens and record every file access in the audit log.</p></div><button onClick={()=>notify("Administrator setup guide downloaded")}><Download/>Setup guide</button></aside>
  </>;
}

type GhostCase = {id:string;employee:string;employeeId:string;signal:string;source:string;risk:"Critical"|"High"|"Medium";amount:string;status:"Payroll held"|"Review required"|"Cleared";details:string;checks:string[]};
const initialGhostCases:GhostCase[] = [
  {id:"GEP-018",employee:"Daniel Wreh",employeeId:"EMP-0217",signal:"Duplicate mobile-money destination",source:"Orange Money · ••4522",risk:"Critical",amount:"162,000 LRD",status:"Payroll held",details:"This destination is also assigned to a former employee whose separation date was July 31.",checks:["Identity verification passed","Destination ownership failed","Employee marked active","No August attendance"]},
  {id:"GEP-017",employee:"Rebecca Johnson",employeeId:"EMP-0194",signal:"Beneficiary-name mismatch",source:"UBA account · ••9812",risk:"High",amount:"980.00 USD",status:"Payroll held",details:"The bank beneficiary name does not match the verified employee legal name.",checks:["NIR identity verified","TIN verified","Bank beneficiary mismatch","Supervisor attestation pending"]},
  {id:"GEP-016",employee:"Abraham Kollie",employeeId:"EMP-0188",signal:"Salary without attendance",source:"August payroll import",risk:"High",amount:"145,000 LRD",status:"Review required",details:"The employee has a full salary but no clock-in, approved leave or field-work attestation for the period.",checks:["Identity verification passed","Payment destination verified","Zero attendance records","No approved leave"]},
  {id:"GEP-015",employee:"Mariama Kamara",employeeId:"EMP-0176",signal:"Legal-name inconsistency",source:"NIR / HR record",risk:"Medium",amount:"124,500 LRD",status:"Review required",details:"The surname in the HR record differs from the verified identity record. Supporting documentation is required.",checks:["NIR match incomplete","TIN name differs","Payment destination verified","Recent profile edit"]},
  {id:"GEP-014",employee:"Joseph Nyumah",employeeId:"EMP-0159",signal:"Inactive worker reintroduced",source:"HR import · Payroll v3",risk:"Critical",amount:"188,000 LRD",status:"Payroll held",details:"A previously separated employee reappeared in the payroll import without an approved rehire record.",checks:["Separation record found","No approved rehire","Prior destination reused","Payroll line newly added"]},
  {id:"GEP-013",employee:"Esther Cooper",employeeId:"EMP-0141",signal:"Unusual pay change",source:"Payroll version comparison",risk:"Medium",amount:"76,000 LRD increase",status:"Review required",details:"Gross pay increased 68% after the payroll cutoff and lacks a supporting compensation approval.",checks:["Identity verified","Attendance approved","Material pay change","Compensation evidence missing"]},
];

export function GhostEmployeeControl({notify}:{notify:(message:string)=>void}) {
  const [cases,setCases] = useState(initialGhostCases);
  const [selectedId,setSelectedId] = useState(initialGhostCases[0].id);
  const [query,setQuery] = useState("");
  const [risk,setRisk] = useState("All");
  const [gateApplied,setGateApplied] = useState(false);
  const selected = cases.find(item=>item.id===selectedId) || cases[0];
  const shown = cases.filter(item=>(risk==="All"||item.risk===risk)&&`${item.employee} ${item.employeeId} ${item.signal}`.toLowerCase().includes(query.toLowerCase()));
  const updateCase = (status:GhostCase["status"], message:string) => {setCases(list=>list.map(item=>item.id===selected.id?{...item,status}:item));notify(message)};
  return <>
    <header className="page-head"><div><span>PAYROLL INTEGRITY</span><h1>Ghost employee prevention</h1><p>Verify that every person is real, active, working and paid only to a destination they control.</p></div><button className="primary compact" onClick={()=>notify("Full workforce verification started")}><RefreshCw/>Run workforce scan</button></header>
    <section className="ghost-scoreboard">
      <article className="ghost-score"><div><ShieldCheck/><span><small>Payroll integrity score</small><b>97.6%</b><em>Strong · 6 records held</em></span></div><div className="ghost-meter"><i style={{width:"97.6%"}}></i></div><p>242 of 248 employees passed identity, employment, attendance and destination controls.</p></article>
      <article><span className="green"><CheckCircle2/></span><div><small>Cleared for payroll</small><b>242</b><em>Verified and active</em></div></article>
      <article><span className="red"><Ban/></span><div><small>Payroll holds</small><b>6</b><em>Cannot be released</em></div></article>
      <article><span className="blue"><WalletCards/></span><div><small>Funds protected</small><b>498,500 LRD</b><em>+ 980.00 USD</em></div></article>
    </section>
    <section className="payroll-gate">
      <div><span><LockKeyhole/></span><div><small>GHOST-PAYROLL GATE</small><h2>{gateApplied?"Protection applied to August payroll":"Six employees must remain on hold"}</h2><p>Cleared employees can continue through payroll. Held records stay excluded until investigation and independent approval are complete.</p></div></div>
      <button className={gateApplied?"applied":""} onClick={()=>{setGateApplied(true);notify("Ghost employee holds applied to payroll v4")}}>{gateApplied?<><Check/>Holds applied</>:<><ShieldCheck/>Apply holds to payroll</>}</button>
    </section>
    <section className="ghost-layout">
      <article className="panel ghost-queue">
        <div className="panel-title"><div><AlertTriangle/><h2>Risk investigation queue</h2></div><i>{cases.filter(item=>item.status!=="Cleared").length} open</i></div>
        <div className="ghost-filters"><div><Search/><input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Search employee or signal"/></div><Select value={risk} onValueChange={setRisk}><SelectTrigger className="mini-select"><SelectValue/></SelectTrigger><SelectContent>{["All","Critical","High","Medium"].map(value=><SelectItem key={value} value={value}>{value} risk</SelectItem>)}</SelectContent></Select></div>
        {shown.map(item=><button key={item.id} className={selected.id===item.id?"selected":""} onClick={()=>setSelectedId(item.id)}><span className={`ghost-risk ${item.risk.toLowerCase()}`}>{item.risk[0]}</span><div><small>{item.id} · {item.employeeId}</small><b>{item.employee}</b><p>{item.signal}</p></div><span><b>{item.amount}</b><i className={item.status.toLowerCase().replaceAll(" ","-")}>{item.status}</i></span><ChevronRight/></button>)}
      </article>
      <article className="panel ghost-detail">
        <header><span className={`ghost-risk ${selected.risk.toLowerCase()}`}>{selected.risk[0]}</span><div><small>{selected.id} · {selected.risk} RISK</small><h2>{selected.employee}</h2><p>{selected.employeeId} · {selected.source}</p></div><i className={selected.status.toLowerCase().replaceAll(" ","-")}>{selected.status}</i></header>
        <aside className="ghost-alert"><AlertTriangle/><div><b>{selected.signal}</b><p>{selected.details}</p></div></aside>
        <h3>Verification evidence</h3><div className="ghost-checks">{selected.checks.map((check,index)=><div key={check}><span className={index<2?"pass":"warn"}>{index<2?<Check/>:<AlertTriangle/>}</span><b>{check}</b><button onClick={()=>notify(`${check} evidence opened`)}>View</button></div>)}</div>
        <div className="ghost-attestation"><label>Supervisor attestation<Select defaultValue="pending"><SelectTrigger className="sheet-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="pending">Pending</SelectItem><SelectItem value="confirmed">Employee actively worked</SelectItem><SelectItem value="not-known">Supervisor does not recognize employee</SelectItem></SelectContent></Select></label><label>HR employment status<Select defaultValue="review"><SelectTrigger className="sheet-select"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="review">Under review</SelectItem><SelectItem value="active">Active and verified</SelectItem><SelectItem value="separated">Separated / inactive</SelectItem><SelectItem value="leave">Approved leave</SelectItem></SelectContent></Select></label></div>
        <label className="case-note">Investigation note<textarea placeholder="Document the evidence reviewed and decision reason."/></label>
        <footer><button onClick={()=>updateCase("Payroll held",`${selected.employee} remains on payroll hold`)}><LockKeyhole/>Keep on hold</button><button onClick={()=>notify("Supporting document request sent")}><FileText/>Request evidence</button><button className="primary compact" onClick={()=>updateCase("Cleared",`${selected.employee} sent for independent clearance approval`)}><Check/>Submit to clear</button></footer>
        <p className="dual-approval"><ShieldCheck/>Clearing a payroll hold requires HR verification plus an independent Finance or Head-of-Organization approval.</p>
      </article>
    </section>
    <section className="ghost-controls">
      <article className="panel"><div className="panel-title"><div><Fingerprint/><h2>Identity & uniqueness</h2></div></div>{[["Verified legal identity","Match NIR or approved government identity"],["Unique employee profile","Block duplicate NIR, TIN and NASSCORP IDs"],["Destination ownership","Match bank or mobile-money beneficiary name"],["Duplicate destination detection","Flag one account used by unrelated workers"]].map(row=><div className="ghost-control" key={row[0]}><span><b>{row[0]}</b><small>{row[1]}</small></span><Switch defaultChecked onCheckedChange={value=>notify(`${row[0]} control ${value?"enabled":"paused"}`)}/></div>)}</article>
      <article className="panel"><div className="panel-title"><div><Activity/><h2>Employment & work proof</h2></div></div>{[["Active employment record","Require approved hire or rehire evidence"],["Supervisor recognition","Named supervisor attests to each direct report"],["Attendance or approved leave","Block salary without work or authorized absence"],["Material-change approval","Recheck identity after pay or destination changes"]].map(row=><div className="ghost-control" key={row[0]}><span><b>{row[0]}</b><small>{row[1]}</small></span><Switch defaultChecked onCheckedChange={value=>notify(`${row[0]} control ${value?"enabled":"paused"}`)}/></div>)}</article>
      <article className="panel"><div className="panel-title"><div><LockKeyhole/><h2>Payroll enforcement</h2></div></div>{[["Automatic payroll hold","Do not calculate or release failed records"],["No self-clearance","Maker cannot clear their own flagged change"],["Recurring workforce scan","Recheck every payroll and after HR imports"],["Recovery review","Investigate prior payments after a confirmed ghost"]].map(row=><div className="ghost-control" key={row[0]}><span><b>{row[0]}</b><small>{row[1]}</small></span><Switch defaultChecked onCheckedChange={value=>notify(`${row[0]} ${value?"enabled":"paused"}`)}/></div>)}</article>
    </section>
    <article className="panel ghost-audit"><div className="panel-title"><div><FileText/><h2>Recent integrity activity</h2></div><button onClick={()=>notify("Ghost prevention audit pack downloaded")}>Download audit pack <Download/></button></div>{[["09:46","System","Held GEP-018 after duplicate destination match"],["09:32","HR Administrator","Confirmed five newly hired employees"],["09:18","System","Compared August payroll v4 with active workforce"],["08:55","Supervisor · Operations","Attested to 34 direct reports"],["Yesterday","Finance Approver","Rejected beneficiary mismatch clearance"]].map(row=><div key={row[0]+row[2]}><span>{row[0]}</span><i><ShieldCheck/></i><p><b>{row[2]}</b><small>{row[1]}</small></p><CheckCircle2/></div>)}</article>
  </>;
}
